In [1]:
import numpy as np
import pandas as pd

print(pd.__version__)

3.0.5

---

1. Pandas Basic

**คำอธิบาย:** Pandas เป็นไลบรารีหลักที่ใช้จัดการข้อมูลเชิงตาราง (tabular data) ใน Python โดยโครงสร้างข้อมูลพื้นฐานที่สุดมี 2 แบบ:
1. **Series** - โครงสร้างข้อมูล 1 มิติ เหมือนคอลัมน์เดียวในตาราง หรืออาร์เรย์ที่มี index เป็นของตัวเอง
2. **DataFrame** - โครงสร้างข้อมูล 2 มิติ เหมือนตาราง Excel ที่มีทั้งแถวและคอลัมน์ สามารถเก็บข้อมูลหลายชนิดได้ในเวลาเดียวกัน

เซลล์นี้แสดงวิธีสร้าง **Series** จาก 3 แหล่งข้อมูล ได้แก่ List, Dictionary และไฟล์ CSV การเข้าถึงค่าทำได้ทั้งแบบดูทั้งก้อนข้อมูล (`print(s)`) หรือดูค่าตำแหน่งเดียวด้วย `.iloc[]` (อ้างอิงตำแหน่งตัวเลข) หรือใช้ label ตรง ๆ เช่น `s["Bob"]` เมื่อ index เป็นข้อความ

In [2]:
### Creating Series ###

## Example 1: From List
scores = [85, 90, 78, 92]
s = pd.Series(scores)
print(s)                                            # Access entire series
print("The first element is", s.iloc[3])                 # Access single element

## Example 2: From Dictionary
scores = {
    "Alice": 85,
    "Bob": 90,
    "Charlie": 78
}
s = pd.Series(scores)
print(s)                                            # Access entire series
print("The second element is", s["Bob"])             # Access single element


## Example 3: From .csv (or .xlsx)
s = pd.read_csv("data_series.csv")["S1"]         
print(s)
print(type(s))

0    85
1    90
2    78
3    92
dtype: int64
The first element is 92
Alice      85
Bob        90
Charlie    78
dtype: int64
The second element is 90
0    0.242507
1    0.958693
2    0.850046
3    0.734946
4    0.937264
5    0.316667
6    0.300098
7    0.452212
8    0.458958
9    0.036284
Name: S1, dtype: float64
<class 'pandas.Series'>

**คำอธิบาย:** เซลล์นี้แสดงวิธีสร้าง **DataFrame** จาก 3 แหล่งข้อมูล เช่นเดียวกับ Series ได้แก่ List (ระบุ `columns` แยกต่างหาก), Dictionary (แต่ละ key กลายเป็นชื่อคอลัมน์โดยอัตโนมัติ) และไฟล์ CSV ผ่าน `pd.read_csv()`

จะเห็นว่า DataFrame ที่อ่านจากไฟล์ CSV สามารถมีคอลัมน์หลายชนิดข้อมูลปะปนกันได้ในตารางเดียว (ตัวเลขทศนิยม, จำนวนเต็ม, ข้อความ) ซึ่งเป็นจุดเด่นของ DataFrame เมื่อเทียบกับ Series ที่เก็บได้เพียงคอลัมน์เดียว

In [3]:
### Creating DataFrames ###

## Example 1: From List
data = [
    ["Alice", 25, 85],
    ["Bob", 30, 90],
    ["Charlie", 22, 78]
]
df = pd.DataFrame(
    data,
    columns=["Name", "Age", "Score"]
)
print(df)

## Example 2: From Dictionary
data = {
    "Name": ["Brad", "Cuper", "Lisa"],
    "Age": [25, 30, 22],
    "Score": [85, 90, 78]
}
df = pd.DataFrame(data)
print(df)


## Example 3: From .csv (or .xlsx)
df = pd.read_csv("data_dataframe.csv")         
print(df)
print(type(df))

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   22     78
    Name  Age  Score
0   Brad   25     85
1  Cuper   30     90
2   Lisa   22     78
       S1  S2   S3    S4  S5
0  0.2425  11  Yes  9.28   0
1  0.9587  33   No  2.47   1
2  0.8500  67  Yes  2.31   0
3  0.7349  36  Yes  0.62   1
4  0.9373  58   No  7.13   1
5  0.3167  80   No  4.52   1
6  0.3001  71   No  2.18   1
7  0.4522  71  Yes  6.68   0
8  0.4590  99   No  5.46   0
9  0.0363  12   No  0.17   1
<class 'pandas.DataFrame'>

**คำอธิบาย:** หลังโหลดข้อมูลเข้ามาแล้ว ควรตรวจสอบข้อมูลเบื้องต้นก่อนนำไปวิเคราะห์ต่อเสมอ โดยมีเมธอดหลักที่ใช้บ่อย ได้แก่
- `df.head()` - ดูข้อมูล 5 แถวแรก (default)
- `df.tail()` - ดูข้อมูล 5 แถวสุดท้าย
- `df.info()` - ดูภาพรวมโครงสร้าง เช่น จำนวนแถว คอลัมน์ ชนิดข้อมูล และค่าที่ไม่ใช่ null ของแต่ละคอลัมน์
- `df.describe()` - ดูค่าสถิติเชิงพรรณนาของคอลัมน์ตัวเลข เช่น mean, std, min, max, quartile

ในตัวอย่างนี้ใช้ `df.head()` เพื่อดูตัวอย่างข้อมูล iris 5 แถวแรก ส่วนบรรทัดอื่นถูก comment ไว้ให้ลองเปิดใช้เองได้

In [4]:
### Inspecting data ###

df = pd.read_csv("iris.csv")  
df.head()
# df.tail()
# df.info()
# df.describe()

   sepal_length  sepal_width  petal_length  petal_width   iris_class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

---

2. Data Selection & Indexing

**คำอธิบาย:** การเลือกคอลัมน์ใน DataFrame ทำได้ 2 แบบที่ให้ผลลัพธ์ต่างกัน:
- `df['column']` (single bracket) - คืนค่าเป็น **Series** (1 มิติ)
- `df[['column1', 'column2']]` (double bracket) - คืนค่าเป็น **DataFrame** (2 มิติ) แม้จะเลือกเพียงคอลัมน์เดียวก็ตาม

ตัวอย่างนี้เลือก 2 คอลัมน์ (`sepal_width`, `sepal_length`) พร้อมกันโดยส่ง list ของชื่อคอลัมน์เข้าไปใน double bracket และลำดับคอลัมน์ในผลลัพธ์จะเรียงตามลำดับที่ระบุใน list ไม่ใช่ลำดับเดิมในไฟล์

In [5]:
### Selecting columns ###

df = pd.read_csv("iris.csv") 
# df['sepal_width']
# df['sepal_length']

df[['sepal_width', 'sepal_length']]
# Take Note
# df['column']                 >>> Series
# df[['column1', 'column2']]   >>> DataFrame

     sepal_width  sepal_length
0            3.5           5.1
1            3.0           4.9
2            3.2           4.7
3            3.1           4.6
4            3.6           5.0
..           ...           ...
145          3.0           6.7
146          2.5           6.3
147          3.0           6.5
148          3.4           6.2
149          3.0           5.9

[150 rows x 2 columns]

**คำอธิบาย:** การเลือกแถวข้อมูลมี 2 เครื่องมือหลักที่ควรแยกให้ออกจากกัน:
- **`.iloc[]`** - เลือกโดยอ้างอิง **ตำแหน่งตัวเลข** (integer position) เหมือน index ของ list/array เช่น `df.iloc[0:5, 0:3]` หมายถึงแถวที่ 0-4 และคอลัมน์ที่ 0-2
- **`.loc[]`** - เลือกโดยอ้างอิงจาก **label** ของ index/คอลัมน์ เช่น หากตั้ง index เป็นตัวอักษร (`"A", "B", "C"`) ต้องใช้ label เหล่านั้นตรง ๆ ใน `.loc[]`

ข้อควรระวัง: ถ้า index ของ DataFrame เป็นตัวเลข (เช่นค่า default 0, 1, 2, ...) `.loc[0]` กับ `.iloc[0]` อาจให้ผลลัพธ์เหมือนกัน แต่ความหมายต่างกันโดยพื้นฐาน - `.loc` ยึด label เป็นหลัก ส่วน `.iloc` ยึดตำแหน่งเป็นหลักเสมอ

In [6]:
### Row selection ###

## Example 1: .iloc[]
df = pd.read_csv("iris.csv") 
df.iloc[0]
df.iloc[0, 1]
df.iloc[[0],[1]]
df.iloc[0:5, 0:3]
df.iloc[5:10, 3:5]


## Example 2: .loc[]
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 22, 28],
    "Score": [85, 90, 78, 92]
}, index=["A", "B", "C", "D"])
print(df)
print()
print(df.loc[["A"]])
print()
print(df.loc["A", "Name"])
print()
print(df.loc["B"]["Score"])                         # OK but not good coding style


## Example 2.1: .loc[] with number index
df = pd.read_csv("iris.csv") 
print(df.loc[0,"sepal_width"])
print(df.loc[0]["sepal_width"])                     # OK but not good coding style

      Name  Age  Score
A    Alice   25     85
B      Bob   30     90
C  Charlie   22     78
D    David   28     92

    Name  Age  Score
A  Alice   25     85

Alice

90
3.5
3.5

**คำอธิบาย:** Boolean filtering คือการกรองแถวข้อมูลด้วยเงื่อนไขที่ให้ผลลัพธ์เป็น True/False เช่น `df["sepal_length"] > 6` จะสร้าง Series ของค่า True/False ตามแต่ละแถว แล้วนำไปใส่ใน `df[...]` เพื่อกรองเฉพาะแถวที่เป็น True

การรวมหลายเงื่อนไขต้องใช้ตัวดำเนินการของ pandas โดยเฉพาะ (ไม่ใช่ `and`/`or` แบบ Python ปกติ):
- `&` แทน AND (ต้องเป็นจริงทุกเงื่อนไข)
- `|` แทน OR (เป็นจริงเงื่อนไขใดเงื่อนไขหนึ่งก็พอ)

แต่ละเงื่อนไขต้องอยู่ในวงเล็บของตัวเองเสมอ เช่น `(df["a"] > 1) & (df["b"] < 2)` นอกจากนี้ยังมีเมธอดช่วยกรองที่สะดวก เช่น `.between()` (กรองช่วงค่า), `.isin()` (กรองว่าค่าตรงกับรายการที่กำหนดหรือไม่) และสามารถใช้ `df.loc[condition, columns]` เพื่อกรองแถวพร้อมเลือกคอลัมน์ที่ต้องการแสดงในคำสั่งเดียว

In [7]:
### Boolean filtering ###

df = pd.read_csv("iris.csv") 
df[df["sepal_length"] > 6]
df[df["sepal_width"] < 3]
df[(df["sepal_length"] > 7) & (df["petal_width"] < 2)]
df[(df["sepal_length"] > 7) | (df["petal_width"] > 2)]
df[df["sepal_length"].between(5, 6)]
df[df["iris_class"] == "Iris-setosa"]
df[df["iris_class"].isin(["Iris-setosa", "Iris-versicolor"])]
df.loc[df["sepal_length"] > 6, ["sepal_length", "sepal_width", "iris_class"]]

     sepal_length  sepal_width       iris_class
50            7.0          3.2  Iris-versicolor
51            6.4          3.2  Iris-versicolor
52            6.9          3.1  Iris-versicolor
54            6.5          2.8  Iris-versicolor
56            6.3          3.3  Iris-versicolor
..            ...          ...              ...
144           6.7          3.3   Iris-virginica
145           6.7          3.0   Iris-virginica
146           6.3          2.5   Iris-virginica
147           6.5          3.0   Iris-virginica
148           6.2          3.4   Iris-virginica

[61 rows x 3 columns]

**คำอธิบาย:** โดย default DataFrame จะมี index เป็นตัวเลขเริ่มจาก 0 ให้อัตโนมัติ แต่บางครั้งเราต้องการใช้คอลัมน์ที่มีความหมาย (เช่น รหัสประจำตัว) เป็น index แทน เพื่อให้ค้นหาแถวด้วย `.loc[]` ได้สะดวกขึ้น

- `df.set_index("ID")` - ตั้งคอลัมน์ `ID` เป็น index ใหม่ (คอลัมน์นั้นจะไม่ปรากฏเป็นคอลัมน์ข้อมูลอีกต่อไป)
- `df.reset_index()` - คืนค่า index กลับมาเป็นตัวเลขปกติ (0, 1, 2, ...) โดยนำ index เดิมกลับมาเป็นคอลัมน์ข้อมูลแทน

ทั้งสองเมธอดนี้คืนค่าเป็น DataFrame ใหม่ (ไม่แก้ไข DataFrame เดิม) เว้นแต่จะระบุ `inplace=True`

In [8]:
### Setting index ###

df = pd.DataFrame({
    "ID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "Score": [85, 90, 78, 92]
})
print(df)

df2 = df.set_index("ID")
print(df2)

df2 = df.reset_index()
print(df2)

    ID     Name  Age  Score
0  101    Alice   20     85
1  102      Bob   21     90
2  103  Charlie   19     78
3  104    David   22     92
        Name  Age  Score
ID
101    Alice   20     85
102      Bob   21     90
103  Charlie   19     78
104    David   22     92
   index   ID     Name  Age  Score
0      0  101    Alice   20     85
1      1  102      Bob   21     90
2      2  103  Charlie   19     78
3      3  104    David   22     92

---

3. Data Cleaning

**คำอธิบาย:** ข้อมูลจริงมักมีค่าที่ขาดหายไป (missing values หรือ `NaN`) ซึ่ง pandas มีเครื่องมือจัดการหลายแบบ:
- `df.isna()` - ตรวจสอบทีละค่าว่าเป็นค่าว่างหรือไม่ (คืนค่า True/False) ต่อด้วย `.sum()` เพื่อนับจำนวนค่าว่างในแต่ละคอลัมน์
- `df.dropna()` - ลบแถวที่มีค่าว่างออกทั้งหมด หรือระบุ `subset=["col"]` เพื่อลบเฉพาะแถวที่คอลัมน์นั้นว่าง
- `df.fillna(value)` - เติมค่าว่างด้วยค่าที่กำหนด เช่นเติมด้วย 0, ค่าเฉลี่ย (`.mean()`) หรือกำหนดค่าต่างกันในแต่ละคอลัมน์ผ่าน dictionary

การเลือกวิธีจัดการขึ้นอยู่กับบริบทของข้อมูล เช่น หากค่าว่างมีน้อยและไม่กระทบการวิเคราะห์อาจลบทิ้งได้ แต่หากข้อมูลมีค่าจำกัดควรเติมค่าแทนเพื่อไม่ให้เสียข้อมูลแถวอื่น ๆ ไป

In [9]:
### Handling missing values ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, None, 22, 28],
    "Score": [85, 90, None, 92]
})
print(df)
print()

## Example 1: .isnull()
print(df.isna())
print()
print(df.isna().sum())
print()

## Example 2: .dropna()
df2 = df.dropna()
print(df2)
print()

df3 = df.dropna(subset=["Age"])
print(df3)
print()


## Example 3: .fillna()
df = df.fillna(0)
print(df)
print()

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Score"] = df["Score"].fillna(df["Score"].mean())
print(df)
print()

df2 = df.fillna({
    "Age": df["Age"].mean(),
    "Score": df["Score"].mean()
})
print(df2)

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   NaN   90.0
2  Charlie  22.0    NaN
3    David  28.0   92.0

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

Name     0
Age      1
Score    1
dtype: int64

    Name   Age  Score
0  Alice  25.0   85.0
3  David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
2  Charlie  22.0    NaN
3    David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   0.0   90.0
2  Charlie  22.0    0.0
3    David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   0.0   90.0
2  Charlie  22.0    0.0
3    David  28.0   92.0

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   0.0   90.0
2  Charlie  22.0    0.0
3    David  28.0   92.0

**คำอธิบาย:** การจัดการชื่อคอลัมน์และเลือกเก็บเฉพาะคอลัมน์ที่จำเป็นเป็นขั้นตอนพื้นฐานในการทำความสะอาดข้อมูล:
- `df.rename(columns={...})` - เปลี่ยนชื่อคอลัมน์เป็นชื่อใหม่ตาม dictionary ที่กำหนด (key คือชื่อเดิม, value คือชื่อใหม่)
- `df.drop(columns=[...])` - ลบคอลัมน์ที่ระบุออกจาก DataFrame หรือใช้ `df.drop("col", axis=1)` ก็ได้ผลลัพธ์เดียวกัน (`axis=1` หมายถึงดำเนินการตามแนวคอลัมน์)

ทั้งสองเมธอดคืนค่าเป็น DataFrame ใหม่โดยไม่แก้ไขต้นฉบับ เว้นแต่จะระบุ `inplace=True`

In [10]:
### Renaming & dropping columns ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "Math": [85, 90, 78, 92],
    "English": [88, 85, 80, 95]
})
print(df)

## Example 1: .rename()
df2 = df.rename(columns={
    "Name": "Student_Name",
    "Math": "Math_Score",
    "English": "English_Score"
})
print(df2)

## Example 2: .drop()
df3 = df.drop(columns=["Age", "English"])
print(df3)

df4 = df.drop("English", axis=1)
print(df4)

      Name  Age  Math  English
0    Alice   20    85       88
1      Bob   21    90       85
2  Charlie   19    78       80
3    David   22    92       95
  Student_Name  Age  Math_Score  English_Score
0        Alice   20          85             88
1          Bob   21          90             85
2      Charlie   19          78             80
3        David   22          92             95
      Name  Math
0    Alice    85
1      Bob    90
2  Charlie    78
3    David    92
      Name  Age  Math
0    Alice   20    85
1      Bob   21    90
2  Charlie   19    78
3    David   22    92

**คำอธิบาย:** `.replace()` ใช้แทนที่ **ค่าข้อมูล (values)** ภายในคอลัมน์ด้วยค่าใหม่ เช่น เปลี่ยน "F" เป็น "Female" โดยสามารถแทนที่ค่าเดียว หรือส่ง dictionary เพื่อแทนที่หลายค่าพร้อมกันในคำสั่งเดียว

ข้อควรระวังคือ `.replace()` ต่างจาก `.fillna()` ตรงที่ `.replace()` ใช้แทนที่ **ค่าที่มีอยู่จริง** (ต้องระบุค่าเดิมกับค่าใหม่) ในขณะที่ `.fillna()` ใช้เติมเฉพาะค่าที่เป็น **NaN/missing value** เท่านั้น (ระบุแค่ค่าที่จะเติม) จึงไม่สามารถใช้แทนกันได้

In [11]:
### Replace Values ###

## Example 1: .replace()
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Gender": ["F", "M", "M", "F"],
    "Grade": ["A", "B", "A", "C"]
})
print(df)
print()

# df["Gender"] = df["Gender"].replace("F", "Female")
# print(df)

# df["Grade"] = df["Grade"].replace({
#     "A": "Excellent",
#     "B": "Good",
#     "C": "Average"
# })
# print(df)

df = df.replace({
    "F": "Female",
    "M": "Male"
})
print(df)

# Important .replace != .fillna()
# df["Age"] = df["Age"].replace(0, 25)          # Two parameters needed
# df["Age"] = df["Age"].fillna(25)              # Single parameter needed

      Name Gender Grade
0    Alice      F     A
1      Bob      M     B
2  Charlie      M     A
3    David      F     C

      Name  Gender Grade
0    Alice  Female     A
1      Bob    Male     B
2  Charlie    Male     A
3    David  Female     C

**คำอธิบาย:** ข้อมูลซ้ำ (duplicate rows) อาจเกิดจากความผิดพลาดตอนรวบรวมข้อมูล ซึ่งควรตรวจสอบและจัดการก่อนวิเคราะห์:
- `df.duplicated()` - คืนค่า Series ของ True/False บอกว่าแต่ละแถวซ้ำกับแถวก่อนหน้าหรือไม่ (แถวที่พบครั้งแรกจะเป็น False เสมอ) ต่อด้วย `.sum()` เพื่อนับจำนวนแถวที่ซ้ำ
- `df.drop_duplicates()` - ลบแถวที่ซ้ำออก เหลือไว้เพียงแถวแรกที่พบ
- สามารถระบุ `subset=["column"]` เพื่อตรวจสอบความซ้ำเฉพาะบางคอลัมน์แทนที่จะเทียบทุกคอลัมน์

หลังจาก `drop_duplicates()` มักตามด้วย `.reset_index(drop=True)` เพื่อจัดเรียง index ใหม่ให้ต่อเนื่องอีกครั้ง

In [12]:
### Detecting duplicates ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Bob", "David", "Alice"],
    "Age": [20, 21, 22, 21, 23, 20],
    "Score": [85, 90, 78, 90, 92, 85]
})
print(df)
print()

## Example 1: .duplicate()
print(df.duplicated())
print(df.duplicated().sum())

duplicates = df[df.duplicated()]
print(duplicates)

df2 = df.drop_duplicates()
print(df2)

df2 = df.drop_duplicates().reset_index(drop=True)           # Drop duplicate usually use with reset index in practice
print(df2)

print(df.duplicated(subset=["Name"]))

      Name  Age  Score
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
3      Bob   21     90
4    David   23     92
5    Alice   20     85

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
2
    Name  Age  Score
3    Bob   21     90
5  Alice   20     85
      Name  Age  Score
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
4    David   23     92
      Name  Age  Score
0    Alice   20     85
1      Bob   21     90
2  Charlie   22     78
3    David   23     92
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

**คำอธิบาย:** บางครั้งข้อมูลที่อ่านเข้ามาอาจมีชนิดข้อมูล (dtype) ไม่ตรงกับที่ต้องการ เช่น ตัวเลขถูกอ่านมาเป็นข้อความ (string) ซึ่งจะทำให้คำนวณทางคณิตศาสตร์ไม่ได้

`df["col"].astype(type)` ใช้แปลงชนิดข้อมูลของคอลัมน์ เช่น `astype(int)`, `astype(float)`, `astype(str)`, `astype(bool)` ควรตรวจสอบ `df.dtypes` ก่อนและหลังแปลงเสมอ เพื่อยืนยันว่าการแปลงชนิดข้อมูลสำเร็จตามที่ต้องการ

In [13]:
### Type conversion ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": ["20", "21", "22"],
    "Score": ["85", "90", "78"],
    "Pass": [1, 1, 0]
})
print(df)
print(df.dtypes)

df["Name"] = df["Name"].astype(str)
df["Age"] = df["Age"].astype(int)
df["Score"] = df["Score"].astype(float)
df["Pass"] = df["Pass"].astype(bool)
print(df)
print(df.dtypes)

      Name Age Score  Pass
0    Alice  20    85     1
1      Bob  21    90     1
2  Charlie  22    78     0
Name       str
Age        str
Score      str
Pass     int64
dtype: object
      Name  Age  Score   Pass
0    Alice   20   85.0   True
1      Bob   21   90.0   True
2  Charlie   22   78.0  False
Name         str
Age        int64
Score    float64
Pass        bool
dtype: object

---

4. Transformation & Aggregation

**คำอธิบาย:** การประยุกต์ใช้ฟังก์ชันกับค่าข้อมูลใน pandas ทำได้ผ่าน `.map()` และ `.apply()` โดยหลักการคล้ายกันคือ นำแต่ละค่าในคอลัมน์ (Series) ไปผ่านฟังก์ชันที่กำหนด แล้วคืนค่าผลลัพธ์ออกมาเป็นคอลัมน์ใหม่

- `.map()` มักใช้กับ Series เพื่อแปลงค่าทีละตัว เช่นใช้ lambda function หรือ dictionary (แปลงค่าตามที่จับคู่ไว้ เช่น "Male" >>> 1)
- `.apply()` ก็ใช้กับ Series ได้เช่นกัน (และใช้กับทั้ง DataFrame เพื่อประยุกต์ฟังก์ชันตามแนวแถวหรือคอลัมน์ได้ด้วย)

ในตัวอย่างนี้ใช้ `.map()` ร่วมกับฟังก์ชันที่นิยามเอง (`add_bonus`) เพื่อบวกค่าคะแนนเพิ่มให้ทุกแถว

In [14]:
### Applying functions ###

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Gender": ["Female", "Male", "Male"],
    "Age": [20, 25, 30],
    "Score": [80, 90, 75]
})
print(df)

# Example 1: .map()
# df["Score"] = df["Score"].map(lambda x: x + 1)      # Apply on each value
# print(df)

# df["Gender"] = df["Gender"].map({
#     "Male": 1,
#     "Female": 0
# })
# print(df)

# Example 2: .apply()
# df["Score"] = df["Score"].apply(lambda x: x + 5)
# print(df)

def add_bonus(x):
    return x + 5
df["Score"] = df["Score"].map(add_bonus)
print(df)

      Name  Gender  Age  Score
0    Alice  Female   20     80
1      Bob    Male   25     90
2  Charlie    Male   30     75
      Name  Gender  Age  Score
0    Alice  Female   20     85
1      Bob    Male   25     95
2  Charlie    Male   30     80

**คำอธิบาย:** `groupby()` ใช้จัดกลุ่มแถวข้อมูลตามค่าของคอลัมน์ที่กำหนด (เช่น จัดกลุ่มพนักงานตามแผนก) เพื่อคำนวณค่าสรุปในแต่ละกลุ่ม ข้อสำคัญคือ **`groupby()` เพียงอย่างเดียวไม่คำนวณอะไร** ต้องต่อด้วยฟังก์ชันรวมค่า (aggregation function) เสมอ เช่น
- `.mean()`, `.sum()` - คำนวณค่าเฉลี่ย/ผลรวมของคอลัมน์ที่เลือกในแต่ละกลุ่ม
- `.agg([...])` - คำนวณหลายค่าสถิติพร้อมกัน เช่น `['mean', 'max', 'min']`
- `.agg({...})` - กำหนดฟังก์ชันรวมค่าต่างกันสำหรับแต่ละคอลัมน์ผ่าน dictionary

ผลลัพธ์จะเป็น DataFrame หรือ Series ใหม่ที่มี index เป็นชื่อกลุ่ม (เช่นชื่อแผนก) แทนที่ index เดิม

In [15]:
### GroupBy operations ###
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Sales', 'Sales', 'IT', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David',
                 'Eve', 'Frank', 'George', 'Helen'],
    'Salary': [50000, 60000, 45000, 48000, 55000, 65000, 52000, 70000],
    'Bonus': [5000, 6000, 4000, 4500, 5500, 6500, 5200, 7000]
}
df = pd.DataFrame(data)
print(df)

df.groupby('Department')['Salary'].mean()           # groupby() does not calculate anything by itself.
df.groupby('Department')['Salary'].sum()
df.groupby('Department')[['Salary', 'Bonus']].sum()
df.groupby('Department')['Salary'].agg(
    ['mean', 'max', 'min']
)
df.groupby('Department').agg({
    'Salary': ['mean', 'max'],
    'Bonus': ['sum', 'mean']
})

  Department Employee  Salary  Bonus
0         IT    Alice   50000   5000
1         IT      Bob   60000   6000
2         HR  Charlie   45000   4000
3         HR    David   48000   4500
4      Sales      Eve   55000   5500
5      Sales    Frank   65000   6500
6         IT   George   52000   5200
7      Sales    Helen   70000   7000

                  Salary         Bonus
                    mean    max    sum         mean
Department
HR          46500.000000  48000   8500  4250.000000
IT          54000.000000  60000  16200  5400.000000
Sales       63333.333333  70000  19000  6333.333333

**คำอธิบาย:** Pivot table เป็นการสรุปข้อมูลในรูปแบบตารางไขว้ (cross-tabulation) คล้ายกับ Pivot Table ใน Excel โดยกำหนด 3 ส่วนหลักผ่าน `pd.pivot_table()`:
- **`values`** - คอลัมน์ที่ต้องการคำนวณ (What do I want to calculate?)
- **`index`** - คอลัมน์ที่ใช้จัดกลุ่มตามแถว (How do I group the rows?)
- **`aggfunc`** - ฟังก์ชันสรุปค่า เช่น `'mean'`, `'sum'` (How do I summarize?)

หากต้องการแยกผลลัพธ์ออกเป็นคอลัมน์ย่อยตามอีกหนึ่งมิติ (เช่นแยกเพศชาย/หญิงในแต่ละแผนก) ให้เพิ่มพารามิเตอร์ **`columns`** เข้าไป ผลลัพธ์ที่ได้จะเป็นตารางที่มีทั้งแถว (index) และคอลัมน์ (columns) แสดงค่าสรุปตามเงื่อนไขทั้งสองมิติพร้อมกัน

In [16]:
### Pivot tables ###	
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Sales', 'Sales', 'IT', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David',
                 'Eve', 'Frank', 'George', 'Helen'],
    'Salary': [50000, 60000, 45000, 48000, 55000, 65000, 52000, 70000],
    'Bonus': [5000, 6000, 4000, 4500, 5500, 6500, 5200, 7000]
}
df = pd.DataFrame(data)
print(df)

# values   >>> What do I want to calculate?
# index    >>> How do I group the rows?
# aggfunc  >>> How do I summarize?
pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    aggfunc='mean'
)

# Columns  >>> How do I separate each value to single column?
df['Gender'] = [
    'F', 'M', 'M', 'F',
    'F', 'M', 'M', 'F'
]
print(df)
pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    columns='Gender',
    aggfunc='mean'
)

  Department Employee  Salary  Bonus
0         IT    Alice   50000   5000
1         IT      Bob   60000   6000
2         HR  Charlie   45000   4000
3         HR    David   48000   4500
4      Sales      Eve   55000   5500
5      Sales    Frank   65000   6500
6         IT   George   52000   5200
7      Sales    Helen   70000   7000
  Department Employee  Salary  Bonus Gender
0         IT    Alice   50000   5000      F
1         IT      Bob   60000   6000      M
2         HR  Charlie   45000   4000      M
3         HR    David   48000   4500      F
4      Sales      Eve   55000   5500      F
5      Sales    Frank   65000   6500      M
6         IT   George   52000   5200      M
7      Sales    Helen   70000   7000      F

Gender            F        M
Department
HR          48000.0  45000.0
IT          50000.0  56000.0
Sales       62500.0  65000.0

**คำอธิบาย:** `df.sort_values()` ใช้เรียงลำดับแถวข้อมูลตามค่าของคอลัมน์ที่ระบุ โดย default จะเรียงจากน้อยไปมาก (ascending) หากต้องการเรียงจากมากไปน้อยให้ระบุ `ascending=False`

สามารถเรียงตามหลายคอลัมน์พร้อมกันได้ผ่าน `by=[...]` และกำหนดทิศทางการเรียงของแต่ละคอลัมน์แยกกันผ่าน `ascending=[...]` **ข้อควรระวัง:** `sort_values()` จะไม่แก้ไข DataFrame เดิม แต่คืนค่าเป็น DataFrame ใหม่ที่เรียงลำดับแล้วเสมอ ต้องเก็บผลลัพธ์ไว้ในตัวแปรใหม่หากต้องการใช้งานต่อ นอกจากนี้ index ของแถวจะติดไปกับข้อมูลเดิม ไม่ได้เรียงใหม่ตามลำดับแถวที่แสดง

In [17]:
### Sorting ###
data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Sales'],
    'Salary': [60000, 45000, 70000, 52000, 55000]
}
df = pd.DataFrame(data)
print(df)


df.sort_values('Salary')                            # Sorting do not change order in original dataframe!
df.sort_values('Salary', ascending=False)

df.sort_values(
    by=['Department', 'Salary'],
    ascending=[True, False]
)

df2 = df.copy()
df2.index = [103, 101, 105, 102, 104]
print(df2)

  Employee Department  Salary
0    Alice         IT   60000
1      Bob         HR   45000
2  Charlie      Sales   70000
3    David         IT   52000
4      Eve      Sales   55000
    Employee Department  Salary
103    Alice         IT   60000
101      Bob         HR   45000
105  Charlie      Sales   70000
102    David         IT   52000
104      Eve      Sales   55000

---

5. Merging and Reshaping Data

**คำอธิบาย:** `pd.concat()` ใช้ต่อรวม DataFrame ตั้งแต่ 2 ตัวขึ้นไปเข้าด้วยกัน โดยกำหนดทิศทางผ่านพารามิเตอร์ `axis`:
- `axis=0` (default) - ต่อรวมตามแนว **แถว** (เพิ่มจำนวนแถว) เหมาะกับข้อมูลที่มีโครงสร้างคอลัมน์เหมือนกัน ควรระบุ `ignore_index=True` เพื่อรีเซ็ต index ใหม่ให้ต่อเนื่อง
- `axis=1` - ต่อรวมตามแนว **คอลัมน์** (เพิ่มจำนวนคอลัมน์) โดยจับคู่แถวตาม index เดิม

หาก DataFrame ที่นำมาต่อกันมีคอลัมน์ไม่ตรงกันทั้งหมด (เช่นตัวอย่างที่ 3) ตำแหน่งที่ไม่มีข้อมูลตรงกันจะถูกเติมด้วย `NaN` โดยอัตโนมัติ

In [18]:
### Concatenation ###

## Example 1: Extend Rows
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['John', 'Jane', 'Bob'],
    'Score': [80, 75, 90]
})
df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['Alice', 'David', 'Emma'],
    'Score': [85, 70, 95]
})

df = pd.concat([df1, df2], axis=0)                              # axis=0 is default, can omit it
df = pd.concat([df1, df2], axis=0, ignore_index=True)           # Recommend to reset index 
print(df)



## Example 2 : Extend columns
name = pd.DataFrame({
    'Name': ['John', 'Jane', 'Bob']
})
score = pd.DataFrame({
    'Score': [80, 75, 90]
})
df = pd.concat([name, score], axis=1)                           # axis=1 cannot omit for extending columns
print(df)



## Example 3: Concat different dataframe
df1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['John', 'Jane']
})
df2 = pd.DataFrame({
    'ID': [3, 4],
    'Score': [90, 80]
})
result = pd.concat([df1, df2], ignore_index=True)
print(result)

   ID   Name  Score
0   1   John     80
1   2   Jane     75
2   3    Bob     90
3   4  Alice     85
4   5  David     70
5   6   Emma     95
   Name  Score
0  John     80
1  Jane     75
2   Bob     90
   ID  Name  Score
0   1  John    NaN
1   2  Jane    NaN
2   3   NaN   90.0
3   4   NaN   80.0

**คำอธิบาย:** การรวมข้อมูลจากหลายตารางเข้าด้วยกันโดยอ้างอิงคีย์ร่วม (เหมือน JOIN ใน SQL) ทำได้ 2 แบบหลัก:
- **`pd.merge()`** - ใช้เมื่อคีย์ที่จะจับคู่อยู่ใน **คอลัมน์** ของทั้งสองตาราง ระบุคอลัมน์ที่ใช้จับคู่ผ่าน `on="column"`
- **`df.join()`** - ใช้เมื่อคีย์ที่จะจับคู่อยู่ใน **index** ของทั้งสองตาราง

ทั้งสองเมธอดกำหนดรูปแบบการรวมผ่านพารามิเตอร์ `how` ได้เหมือนกัน:
- `'inner'` - เก็บเฉพาะคีย์ที่มีอยู่ในทั้งสองตาราง
- `'outer'` - เก็บคีย์ทั้งหมดจากทั้งสองตาราง (ตำแหน่งที่ไม่มีข้อมูลจะเป็น `NaN`)
- `'left'` - ยึดคีย์จากตารางซ้ายเป็นหลัก
- `'right'` - ยึดคีย์จากตารางขวาเป็นหลัก

In [19]:
### Merging/Joining ###

##Example 1: Merge() 
# students = pd.DataFrame({
#     'student_id': [101, 102, 103, 104],
#     'name': ['Alice', 'Bob', 'Charlie', 'David']
# })
# scores = pd.DataFrame({
#     'student_id': [101, 102, 103, 105],
#     'score': [85, 72, 90, 65]
# })

# result = pd.merge(students, scores, on='student_id', how='inner')             # If key is in column
# result = pd.merge(students, scores, on='student_id', how='outer')
# result = pd.merge(students, scores, on='student_id', how='left')
# result = pd.merge(students, scores, on='student_id', how='right')
# print(result)


##Example 2: Join() 
students = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David']
}, index=[101, 102, 103, 104])

scores = pd.DataFrame({
    'score': [85, 72, 90, 65]
}, index=[101, 102, 103, 105])

result = students.join(scores)                                                  # If key is in index
result = students.join(scores, how='right')                     
result = students.join(scores, how='inner')
result = students.join(scores, how='outer')
print(result)

        name  score
101    Alice   85.0
102      Bob   72.0
103  Charlie   90.0
104    David    NaN
105      NaN   65.0

**คำอธิบาย:** การแปลงรูปแบบตาราง (reshaping) เป็นการจัดโครงสร้างข้อมูลใหม่โดยไม่เปลี่ยนเนื้อหา ใช้บ่อยเมื่อต้องเตรียมข้อมูล ให้อยู่ในรูปแบบที่เหมาะกับการวิเคราะห์หรือพล็อตกราฟ:
- **`.melt()`** - แปลงข้อมูลจากรูปแบบ "wide" (แต่ละตัวแปรเป็นคอลัมน์) ให้เป็นรูปแบบ "long" (รวมคอลัมน์ตัวแปรเป็นแถวเดียว) โดยระบุ `id_vars` (คอลัมน์ที่คงไว้), `var_name` (ชื่อคอลัมน์ใหม่ที่เก็บชื่อตัวแปรเดิม) และ `value_name` (ชื่อคอลัมน์ใหม่ที่เก็บค่า)
- **`.stack()`** - แปลงคอลัมน์ให้กลายเป็นระดับหนึ่งของ index (บีบข้อมูลจากแนวนอนเป็นแนวตั้ง)
- **`.unstack()`** - ทำสิ่งตรงข้ามกับ `.stack()` คือแปลง index กลับมาเป็นคอลัมน์

In [20]:
### Reshaping ###

## Example 1: .melt()
# df = pd.DataFrame({
#     'Name': ['John', 'Jane', 'Bob'],
#     'Math': [80, 75, 90],
#     'English': [85, 80, 88],
#     'Science': [90, 85, 92]
# })
# df_long = df.melt(
#     id_vars='Name',                               # Remaining column 
#     var_name='Subject',                           # New column name of original columns
#     value_name='Score'                            # New column for the data
# )
# print(df_long)



# Example 2: .stack() and .unstack
df = pd.DataFrame({
    'Name': ['John', 'Jane', 'Bob'],
    'Math': [80, 75, 90],
    'English': [85, 80, 88],
    'Science': [90, 85, 92]
})
df = df.set_index('Name')
print(df)

result = df.stack()                                # Columns convert to Index 
print(result)

result = result.unstack()                           # Index convert to Columns
print(result)

      Math  English  Science
Name
John    80       85       90
Jane    75       80       85
Bob     90       88       92
Name
John  Math       80
      English    85
      Science    90
Jane  Math       75
      English    80
      Science    85
Bob   Math       90
      English    88
      Science    92
dtype: int64
      Math  English  Science
Name
John    80       85       90
Jane    75       80       85
Bob     90       88       92

---

**คำอธิบาย:** ส่วนนี้เป็นการนำเมธอดที่เรียนไปทั้งหมดมาทดลองใช้กับชุดข้อมูลจริง (`ifood.xlsx`) เริ่มจากอ่านไฟล์ Excel ด้วย `pd.read_excel()` แล้วดูตัวอย่างข้อมูล 12 แถวแรกด้วย `df.head(12)` เพื่อสำรวจโครงสร้างคอลัมน์ทั้งหมดของชุดข้อมูลก่อนนำไปวิเคราะห์ต่อ

In [8]:
import pandas as pd
df = pd.read_excel("ifood.xlsx")
df.head(12)

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days,Marital,Education
0,1,58138,0,0,58,635,88,546,172,88,...,0,0,0,0,0,1,63,2822,Single,Graduation
1,2,46344,1,1,38,11,1,6,2,1,...,0,0,0,0,0,0,66,2272,Single,Graduation
2,3,71613,0,0,26,426,49,127,111,21,...,0,0,0,0,0,0,55,2471,Together,Graduation
3,4,26646,1,0,26,11,4,20,10,3,...,0,0,0,0,0,0,36,2298,Together,Graduation
4,5,58293,1,0,94,173,43,118,46,27,...,0,0,0,0,0,0,39,2320,Married,PhD
5,6,62513,0,1,16,520,42,98,0,42,...,0,0,0,0,0,0,53,2452,Together,Master
6,7,55635,0,1,34,235,65,164,50,49,...,0,0,0,0,0,0,49,2752,Divorced,Graduation
7,8,33454,1,0,32,76,10,56,3,1,...,0,0,0,0,0,0,35,2576,Married,PhD
8,9,30351,1,0,19,14,0,24,3,3,...,0,0,0,0,0,1,46,2547,Together,PhD
9,10,5648,1,1,68,28,0,6,1,1,...,0,0,0,0,0,0,70,2267,Together,PhD
10,11,7500,0,0,59,6,16,11,11,1,...,0,0,0,0,0,0,44,2752,Married,Basic
11,12,63033,0,0,82,194,61,480,225,112,...,0,0,0,0,0,0,61,2385,Divorced,Graduation

**คำอธิบาย:** `df.info()` แสดงภาพรวมโครงสร้างของ DataFrame ในคำสั่งเดียว ได้แก่ จำนวนแถวทั้งหมด, รายชื่อคอลัมน์, จำนวนค่าที่ไม่ใช่ null (Non-Null Count) ของแต่ละคอลัมน์, ชนิดข้อมูล (Dtype) และหน่วยความจำที่ใช้ เป็นคำสั่งที่ควรใช้ตรวจสอบทุกครั้งหลังโหลดข้อมูลใหม่ เพื่อดูว่ามีคอลัมน์ใดมีค่าขาดหายไปหรือมีชนิดข้อมูลผิดปกติหรือไม่

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   No                   2205 non-null   int64
 1   Income               2205 non-null   int64
 2   Kidhome              2205 non-null   int64
 3   Teenhome             2205 non-null   int64
 4   Recency              2205 non-null   int64
 5   MntWines             2205 non-null   int64
 6   MntFruits            2205 non-null   int64
 7   MntMeatProducts      2205 non-null   int64
 8   MntFishProducts      2205 non-null   int64
 9   MntSweetProducts     2205 non-null   int64
 10  MntGoldProds         2205 non-null   int64
 11  NumDealsPurchases    2205 non-null   int64
 12  NumWebPurchases      2205 non-null   int64
 13  NumCatalogPurchases  2205 non-null   int64
 14  NumStorePurchases    2205 non-null   int64
 15  NumWebVisitsMonth    2205 non-null   int64
 16  AcceptedCmp3         2205 non-null   int64
 17  AcceptedCmp4         2205 non-null   int64
 18  AcceptedCmp5         2205 non-null   int64
 19  AcceptedCmp1         2205 non-null   int64
 20  AcceptedCmp2         2205 non-null   int64
 21  Complain             2205 non-null   int64
 22  Response             2205 non-null   int64
 23  Age                  2205 non-null   int64
 24  Customer_Days        2205 non-null   int64
 25  Marital              2205 non-null   str
 26  Education            2205 non-null   str
dtypes: int64(25), str(2)
memory usage: 465.2 KB

**คำอธิบาย:** `df.describe()` แสดงค่าสถิติเชิงพรรณนา (descriptive statistics) ของคอลัมน์ที่เป็นตัวเลขทั้งหมดโดยอัตโนมัติ ได้แก่ จำนวนข้อมูล (count), ค่าเฉลี่ย (mean), ส่วนเบี่ยงเบนมาตรฐาน (std), ค่าต่ำสุด/สูงสุด (min/max) และค่าเปอร์เซ็นไทล์ (25%, 50%, 75%) ช่วยให้เห็นภาพรวมการกระจายตัวของข้อมูลแต่ละคอลัมน์ได้อย่างรวดเร็ว

In [10]:
df.describe()

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days
count,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,...,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.00000,2205.000000,2205.000000
mean,1103.000000,51622.094785,0.442177,0.506576,49.009070,306.164626,26.403175,165.312018,37.756463,27.128345,...,5.336961,0.073923,0.074376,0.073016,0.064399,0.013605,0.009070,0.15102,51.095692,2512.718367
std,636.672993,20713.063826,0.537132,0.544380,28.932111,337.493839,39.784484,217.784507,54.824635,41.130468,...,2.413535,0.261705,0.262442,0.260222,0.245518,0.115872,0.094827,0.35815,11.705801,202.563647
min,1.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,24.000000,2159.000000
25%,552.000000,35196.000000,0.000000,0.000000,24.000000,24.000000,2.000000,16.000000,3.000000,1.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,43.000000,2339.000000
50%,1103.000000,51287.000000,0.000000,0.000000,49.000000,178.000000,8.000000,68.000000,12.000000,8.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,50.000000,2515.000000
75%,1654.000000,68281.000000,1.000000,1.000000,74.000000,507.000000,33.000000,232.000000,50.000000,34.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,61.000000,2688.000000
max,2205.000000,113734.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,262.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,80.000000,2858.000000

**คำอธิบาย:** ทบทวนการเลือกหลายคอลัมน์พร้อมกันด้วย double bracket (`df[[...]]`) จากชุดข้อมูล iris ซึ่งคืนค่าเป็น DataFrame ที่มีเฉพาะคอลัมน์ `sepal_width` และ `sepal_length` ตามลำดับที่ระบุใน list

In [14]:
df = pd.read_csv("iris.csv")
# df['sepal_width']
# df['sepal_length']
df[['sepal_width', 'sepal_length']]

     sepal_width  sepal_length
0            3.5           5.1
1            3.0           4.9
2            3.2           4.7
3            3.1           4.6
4            3.6           5.0
..           ...           ...
145          3.0           6.7
146          2.5           6.3
147          3.0           6.5
148          3.4           6.2
149          3.0           5.9

[150 rows x 2 columns]

**คำอธิบาย:** ทบทวนการอ่านไฟล์ Excel ด้วย `pd.read_excel()` อีกครั้ง แล้วแสดงตัวอย่างข้อมูล 5 แถวแรกด้วย `df.head()` เพื่อยืนยันว่าข้อมูลถูกโหลดเข้ามาอย่างถูกต้องก่อนนำไปใช้งานต่อ

In [15]:
df = pd.read_excel("ifood.xlsx")

df.head()

,No,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Customer_Days,Marital,Education
0,1,58138,0,0,58,635,88,546,172,88,...,0,0,0,0,0,1,63,2822,Single,Graduation
1,2,46344,1,1,38,11,1,6,2,1,...,0,0,0,0,0,0,66,2272,Single,Graduation
2,3,71613,0,0,26,426,49,127,111,21,...,0,0,0,0,0,0,55,2471,Together,Graduation
3,4,26646,1,0,26,11,4,20,10,3,...,0,0,0,0,0,0,36,2298,Together,Graduation
4,5,58293,1,0,94,173,43,118,46,27,...,0,0,0,0,0,0,39,2320,Married,PhD